export enum PermissionType {
  USERS = 'USERS',
  PERMISSIONS = 'PERMISSIONS',
  ROLES = 'ROLES',
  GAME_COLLECTIONS = 'GAME_COLLECTIONS',
  COLLECTION_SUPERUSER = 'COLLECTION_SUPERUSER',
  ADMIN_PANEL = 'ADMIN_PANEL',
}
